# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_project/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/vivado_project/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/vivado_project/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/timescale.v
set_property file_type "Verilog Header" [get_files D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/timescale.v]
set_property is_global_include true [get_files D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/timescale.v]
read_verilog -library xil_defaultlib {
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/FifoBuffer.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/async_fifo.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/clock_generator.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/fftTop.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/mgtTop.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_defines.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_alu.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_cfgr.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_cpu.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_ctrl.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dc_fsm.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dc_ram.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dc_tag.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dc_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dmmu_tlb.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dmmu_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_dpram_256x32.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_du.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_except.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_freeze.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_genpc.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_gmultp2_32x32.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_ic_fsm.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_ic_ram.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_ic_tag.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_ic_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_if.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_immu_tlb.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_immu_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_iwb_biu.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_lsu.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_mem2reg.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_mult_mac.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_operandmuxes.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_pic.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_pm.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_qmem_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_reg2mem.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_rf.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_rfram_generic.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_sb.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_sb_fifo.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_spram_2048x32_bw.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_spram_512x20.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_spram_64x14.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_spram_64x22.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_spram_64x24.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_sprs.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_tt.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_wb_biu.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/or1200/or1200_wbmux.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt_frame_check.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt_frame_gen.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt_usrclk_source.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/rtlRam.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_defines.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_crc16.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_crc5.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_ep_rf.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_idma.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_mem_arb.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_pa.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_pd.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_pe.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_pl.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_rf.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_utmi_if.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_utmi_ls.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/usbf/usbf_wb.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_defines.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_arb.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_master_if.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_msel.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_pri_dec.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_pri_enc.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_rf.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_slave_if.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_top.v
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/top.v
}
read_vhdl -library bftLib {
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bftLib/bft_package.vhdl
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bftLib/core_transform.vhdl
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bftLib/round_1.vhdl
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bftLib/round_2.vhdl
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bftLib/round_3.vhdl
  D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bftLib/round_4.vhdl
}
read_vhdl -library xil_defaultlib D:/vivado_project/project_1/project_1.srcs/sources_1/imports/Sources/bft.vhdl
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_project/project_1/project_1.srcs/constrs_2/imports/kintex7/top_full.xdc
set_property used_in_implementation false [get_files D:/vivado_project/project_1/project_1.srcs/constrs_2/imports/kintex7/top_full.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7k70tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
